In [12]:
import os
from pathlib import Path

import geopandas as gpd
import pandas as pd
import sqlalchemy

In [11]:
engine = sqlalchemy.create_engine(
    f"postgresql+psycopg2://{os.environ['POSTGRES_USER']}:{os.environ['POSTGRES_PASSWORD']}@{os.environ['POSTGRES_HOST']}:{os.environ['POSTGRES_PORT']}/{os.environ['POSTGRES_DB']}"
)

In [2]:
data_path = Path(os.environ["DATA_PATH"])

In [49]:
df_1995 = gpd.read_file(data_path / "raws" / "1995" / "Municipios_1995.shp").assign(
    cvegeo=lambda df: (
        df["CVE_ENT"].astype(str).str.zfill(2) + df["CVE_MUN"].astype(str).str.zfill(3)
    )
)
df_1990 = pd.read_csv(
    data_path / "raws" / "1990" / "ITER_NALTXT90.txt", sep="\t", encoding="latin-1"
)

C:\Users\lain\AppData\Local\Temp\ipykernel_30220\2138658618.py:2: DtypeWarning: Columns (6,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1990 = pd.read_csv(data_path / "raws" / "1990" / "ITER_NALTXT90.txt", sep="\t", encoding="latin-1")

In [50]:
temp = df_1990.loc[lambda df: df["mun"] != 0]
muns_1990 = set(
    (temp["entidad"].astype(str).str.zfill(2) + temp["mun"].astype(str).str.zfill(3))
    .unique()
    .tolist()
)

In [51]:
muns_1995 = set(df_1995["cvegeo"].unique().tolist())

In [68]:
print(
    "\n".join(
        [
            "-" + " - ".join(x)
            for x in df_1995.loc[
                lambda df: df["cvegeo"].isin(muns_1995 - muns_1990),
                ["NOM_ENT", "NOM_MUN"],
            ].to_numpy()
        ]
    )
)

-Aguascalientes - Llano, El
-Aguascalientes - San Francisco de los Romo
-Baja California - Playas de Rosarito
-Baja California Sur - Loreto
-Guerrero - Acatepec
-México - Valle de Chalco Solidaridad
-Quintana Roo - Solidaridad
-San Luis Potosí - Matlapa
-San Luis Potosí - Naranjo, El
-Tlaxcala - Benito Juárez
-Tlaxcala - Emiliano Zapata
-Tlaxcala - Lázaro Cárdenas
-Tlaxcala - Magdalena Tlaltelulco, La
-Tlaxcala - San Damián Texoloc
-Tlaxcala - San Francisco Tetlanohcan
-Tlaxcala - San Jerónimo Zacualpan
-Tlaxcala - San José Teacalco
-Tlaxcala - San Juan Huactzinco
-Tlaxcala - San Lorenzo Axocomanitla
-Tlaxcala - San Lucas Tecopilco
-Tlaxcala - Santa Ana Nopalucan
-Tlaxcala - Santa Apolonia Teacalco
-Tlaxcala - Santa Catarina Ayometla
-Tlaxcala - Santa Cruz Quilehtla
-Tlaxcala - Santa Isabel Xiloxoxtla

In [58]:
df_1990.loc[lambda df: (df["entidad"] == 29) & (df["mun"] != 0) & (df["loc"] == 0)]

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,longitud,latitud,altitud,p_total,...,prom_cua,pared_la,techo_la,piso_tie,viv_1_c,viv_2_c,c_agua_ent,c_drenaje,c_e_elect,viv_pprop
135263,29,Tlaxcala,1,Amaxac de Guerrero,0,TOTAL MUNICIPAL,NaN,NaN,NaN,6192.0,...,1.65,5,58,1019,108,199,1059,622,1066,966
135268,29,Tlaxcala,2,Apetatitlán de Antonio Carvajal,0,TOTAL MUNICIPAL,NaN,NaN,NaN,8990.0,...,1.34,6,72,1616,92,227,1619,1278,1665,1368
135273,29,Tlaxcala,3,Atlangatepec,0,TOTAL MUNICIPAL,NaN,NaN,NaN,4255.0,...,1.81,6,114,669,105,153,685,225,711,705
135303,29,Tlaxcala,4,Atltzayanca,0,TOTAL MUNICIPAL,NaN,NaN,NaN,11819.0,...,2,214,269,1564,149,545,1670,769,1823,1839
135350,29,Tlaxcala,5,Apizaco,0,TOTAL MUNICIPAL,NaN,NaN,NaN,51744.0,...,1.25,257,768,10204,657,1246,9785,9040,10372,7058
135360,29,Tlaxcala,6,Calpulalpan,0,TOTAL MUNICIPAL,NaN,NaN,NaN,29150.0,...,1.52,85,1015,4820,391,992,5234,4995,5211,4205
135436,29,Tlaxcala,7,El Carmen Tequexquitla,0,TOTAL MUNICIPAL,NaN,NaN,NaN,9749.0,...,2.47,105,285,1174,293,462,1287,404,1355,1429
135441,29,Tlaxcala,8,Cuapiaxtla,0,TOTAL MUNICIPAL,NaN,NaN,NaN,8592.0,...,1.90,93,298,1233,181,309,1416,689,1379,1361
135472,29,Tlaxcala,9,Cuaxomulco,0,TOTAL MUNICIPAL,NaN,NaN,NaN,3365.0,...,1.95,3,67,488,74,118,541,161,542,491
135478,29,Tlaxcala,10,Chiautempan,0,TOTAL MUNICIPAL,NaN,NaN,NaN,61144.0,...,1.65,75,699,9589,994,1699,9973,6781,10495,8895
135489,29,Tlaxcala,11,Muñoz de Domingo Arenas,0,TOTAL MUNICIPAL,NaN,NaN,NaN,3051.0,...,1.69,2,89,512,61,111,560,376,539,509
135497,29,Tlaxcala,12,Españita,0,TOTAL MUNICIPAL,NaN,NaN,NaN,6293.0,...,1.78,11,230,743,108,287,1051,275,1095,1089
135528,29,Tlaxcala,13,Huamantla,0,TOTAL MUNICIPAL,NaN,NaN,NaN,51989.0,...,1.91,486,1196,7511,816,1619,7672,5492,7921,6649
135608,29,Tlaxcala,14,Hueyotlipan,0,TOTAL MUNICIPAL,NaN,NaN,NaN,11051.0,...,1.88,1,201,1591,175,349,1752,937,1767,1702
135638,29,Tlaxcala,15,Ixtacuixtla de Mariano Matamoros,0,TOTAL MUNICIPAL,NaN,NaN,NaN,30663.0,...,1.69,10,496,4646,523,1168,4637,2272,5472,5159
135697,29,Tlaxcala,16,Ixtenco,0,TOTAL MUNICIPAL,NaN,NaN,NaN,5356.0,...,1.77,23,76,910,108,288,1014,686,1038,988
135699,29,Tlaxcala,17,Mazatecochco de José María Morelos,0,TOTAL MUNICIPAL,NaN,NaN,NaN,6320.0,...,1.93,4,67,845,58,362,1035,712,1053,1095
135701,29,Tlaxcala,18,Contla de Juan Cuamatzi,0,TOTAL MUNICIPAL,NaN,NaN,NaN,22380.0,...,2.18,29,384,2587,498,891,2846,1021,3356,3258
135709,29,Tlaxcala,19,Tepetitla de Lardizábal,0,TOTAL MUNICIPAL,NaN,NaN,NaN,11235.0,...,1.88,12,193,1636,245,414,1647,1260,1911,1661
135720,29,Tlaxcala,20,Sanctórum de Lázaro Cárdenas,0,TOTAL MUNICIPAL,NaN,NaN,NaN,9754.0,...,1.77,6,615,1394,147,467,1754,1536,1706,1584
135738,29,Tlaxcala,21,Nanacamilpa de Mariano Arista,0,TOTAL MUNICIPAL,NaN,NaN,NaN,12837.0,...,1.55,6,351,2111,208,467,2437,2203,2430,2037
135774,29,Tlaxcala,22,Acuamanala de Miguel Hidalgo,0,TOTAL MUNICIPAL,NaN,NaN,NaN,6989.0,...,1.98,13,35,1062,154,231,1200,361,1162,1143
135780,29,Tlaxcala,23,Natívitas,0,TOTAL MUNICIPAL,NaN,NaN,NaN,21485.0,...,1.89,29,223,3173,356,759,2499,1635,3598,3431
135797,29,Tlaxcala,24,Panotla,0,TOTAL MUNICIPAL,NaN,NaN,NaN,17903.0,...,1.44,26,174,2608,203,653,2694,1598,3206,3099
135807,29,Tlaxcala,25,San Pablo del Monte,0,TOTAL MUNICIPAL,NaN,NaN,NaN,40917.0,...,2.10,130,633,5582,621,1277,5402,3430,5562,5910
135812,29,Tlaxcala,26,Santa Cruz Tlaxcala,0,TOTAL MUNICIPAL,NaN,NaN,NaN,10522.0,...,1.76,5,184,1652,169,417,1706,799,1762,1616
135823,29,Tlaxcala,27,Tenancingo,0,TOTAL MUNICIPAL,NaN,NaN,NaN,9749.0,...,1.90,14,166,1365,92,300,1410,997,1508,1459
135825,29,Tlaxcala,28,Teolocholco,0,TOTAL MUNICIPAL,NaN,NaN,NaN,13693.0,...,2.11,23,205,1832,296,431,2008,780,2043,2104
135830,29,Tlaxcala,29,Tepeyanco,0,TOTAL MUNICIPAL,NaN,NaN,NaN,16942.0,...,2,7,118,2092,262,544,2064,1243,2552,2480
135842,29,Tlaxcala,30,Terrenate,0,TOTAL MUNICIPAL,NaN,NaN,NaN,13660.0,...,2.19,69,201,1668,173,571,1860,894,1919,2045
135905,29,Tlaxcala,31,Tetla de la Solidaridad,0,TOTAL MUNICIPAL,NaN,NaN,NaN,15429.0,...,1.61,33,399,2523,289,525,2543,1324,2715,2561
135933,29,Tlaxcala,32,Tetlatlahuca,0,TOTAL MUNICIPAL,NaN,NaN,NaN,15801.0,...,1.68,9,90,2544,249,491,2576,1452,2747,2686
135940,29,Tlaxcala,33,Tlaxcala,0,TOTAL MUNICIPAL,NaN,NaN,NaN,50492.0,...,1.23,87,423,9808,628,1055,9748,8118,9897,7781
135944,29,Tlaxcala,34,Tlaxco,0,TOTAL MUNICIPAL,NaN,NaN,NaN,27089.0,...,1.81,31,552,3682,323,1285,4105,2090,4477,4218
136078,29,Tlaxcala,35,Tocatlán,0,TOTAL MUNICIPAL,NaN,NaN,NaN,3729.0,...,1.87,2,93,519,46,84,559,233,561,537
136081,29,Tlaxcala,36,Totolac,0,TOTAL MUNICIPAL,NaN,NaN,NaN,15200.0,...,1.35,20,106,2814,233,437,2761,2257,2888,2301
136084,29,Tlaxcala,37,Ziltlaltépec de Trinidad Sánchez Santos,0,TOTAL MUNICIPAL,NaN,NaN,NaN,7847.0,...,2.49,32,290,910,239,328,923,590,1159,1081
136088,29,Tlaxcala,38,Tzompantepec,0,TOTAL MUNICIPAL,NaN,NaN,NaN,10406.0,...,1.94,28,252,1469,220,306,1416,316,1595,1561
136098,29,Tlaxcala,39,Xaloztoc,0,TOTAL MUNICIPAL,NaN,NaN,NaN,13500.0,...,1.84,16,344,1814,209,324,2042,819,2054,1972
136101,29,Tlaxcala,40,Xaltocan,0,TOTAL MUNICIPAL,NaN,NaN,NaN,8777.0,...,1.75,5,253,1228,176,340,1487,528,1548,1489
136121,29,Tlaxcala,41,Papalotla de Xicohténcatl,0,TOTAL MUNICIPAL,NaN,NaN,NaN,17222.0,...,1.64,32,129,2880,240,580,2894,2040,3002,2647
136124,29,Tlaxcala,42,Xicohtzinco,0,TOTAL MUNICIPAL,NaN,NaN,NaN,8563.0,...,1.60,14,77,1350,97,296,1197,1139,1493,1372
136126,29,Tlaxcala,43,Yauhquemehcan,0,TOTAL MUNICIPAL,NaN,NaN,NaN,12783.0,...,1.58,16,238,2068,204,377,2052,1046,2196,1917
136135,29,Tlaxcala,44,Zacatelco,0,TOTAL MUNICIPAL,NaN,NaN,NaN,36650.0,...,1.80,46,215,5659,623,1261,5611,3943,6077,5591

In [78]:
df_1990[
    lambda df: (
        (df["loc"] == 0) & (df["nom_mun"].str.casefold().str.contains("tetlatlahuca"))
    )
]

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,longitud,latitud,altitud,p_total,...,prom_cua,pared_la,techo_la,piso_tie,viv_1_c,viv_2_c,c_agua_ent,c_drenaje,c_e_elect,viv_pprop
135933,29,Tlaxcala,32,Tetlatlahuca,0,TOTAL MUNICIPAL,NaN,NaN,NaN,15801.0,...,1.68,9,90,2544,249,491,2576,1452,2747,2686

In [52]:
muns_1995 - muns_1990

{'01010',
 '01011',
 '02005',
 '03009',
 '12076',
 '15122',
 '23008',
 '24057',
 '24058',
 '29045',
 '29046',
 '29047',
 '29048',
 '29049',
 '29050',
 '29051',
 '29052',
 '29053',
 '29054',
 '29055',
 '29056',
 '29057',
 '29058',
 '29059',
 '29060'}